# Default values for k8s-bootstrap-wrapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


nameOverride: ""
fullnameOverride: ""

bootstrap-init:
  enabled: false

# See https://github.com/argoproj/argo-helm/blob/master/charts/argo-workflows/values.yaml
argo-workflows:
  enabled: false
  singleNamespace: false
  # useDefaultArtifactRepo: true
  # artifactRepository:
  #   archiveLogs: true
  #   s3:
  #     accessKeySecret:
  #       key: accesskey
  #       name: minio
  #     secretKeySecret:
  #       key: secretkey
  #       name: minio
  #     bucket: argo-workflows
  #     endpoint: cluster-minio.minio.svc:9000
  #     insecure: true
  controller:
    containerRuntimeExecutor: pns
  server:
    extraArgs:
      - --auth-mode=server
    ingress:
      enabled: true
      annotations:
        - ingress.kubernetes.io/protocol: http
      # labels: {}
      # ingressClassName: ""
      hosts:
        - argoworkflow.public.k8s.local
  workflow:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::054273887971:role/baas-argo-workflow-service-account"

global:
  serviceAccount:
    name: cluster-boot-strapper