---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: helm-template
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "150"
    #"helm.sh/hook-delete-policy": before-hook-creation
spec:
  entrypoint: main
  securityContext:
    runAsNonRoot: true
    runAsUser: 10010

############# inputs Definition #################
  templates:
  - name: main
    inputs:
      parameters:
      - name: releaseName
      - name: chart
      - name: namespace
      - name: version
      - name: url
      - name: configMapName
      - name: repoName
        value: repo
    initContainers:
    - name: registy-add
      image: alpine/helm
      env:
      - name: HELM_CACHE_HOME
        value: /tmp/.helm/cache
      - name: HELM_CONFIG_HOME
        value: /tmp/.helm/config
      command: ["helm"]
      args:
       - "repo"
       - "add"
       - "{{inputs.parameters.repoName}}"
       - "{{inputs.parameters.url}}"
      mirrorVolumeMounts: true
    container:
      image: alpine/helm
      env:
      - name: HELM_CACHE_HOME
        value: /tmp/.helm/cache
      - name: HELM_CONFIG_HOME
        value: /tmp/.helm/config
      command: [ "helm" ]
      args: 
        - "upgrade"
        - "--install"
        - "{{inputs.parameters.releaseName}}"
        - "{{inputs.parameters.repoName}}/{{inputs.parameters.chart}}"
        - "--wait"
        - "-n"
        - "{{inputs.parameters.namespace}}"
        - "--create-namespace=true"
        - "--version"
        - "{{inputs.parameters.version}}"
        - "-f"
        - "/tmp/yaml/chart-values.yaml"
        - "--debug"
        - "--timeout"
        - "600s"
      volumeMounts:
      - name: cache
        mountPath: /tmp/.helm
      - name: config-yaml
        mountPath: /tmp/yaml
    volumes:
    - name: cache
      emptyDir: {}
    - name: config-yaml
      configMap:
        name: "{{inputs.parameters.configMapName}}"
