apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  annotations:
     workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: |
    s3:
      accessKeySecret:
        key: accesskey
        name: minio
      secretKeySecret:
        key: argo-artifacts
        name: argo-artifacts
      bucket: argo-artifacts
      endpoint: argo-artifacts.{{.Release.Namespace}}.svc:9000
      insecure: true
