# This template demonstrates a workflow of workflows.
# Workflow triggers one or more workflow and manage it.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-of-workflows
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    #"helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "200"
spec:
  entrypoint: main
  serviceAccountName: "{{ .Values.global.serviceAccount.name }}"
  securityContext:
    runAsNonRoot: true
    runAsUser: 10010
  arguments:
    parameters:
    - name: namespaces
      value: |
        {{- .Values.workflow.namespaces | toJson | nindent  8 }}
    - name: helm
      value: |
        [ {{- .Values.workflow.helm | toJson | nindent  8 }} ]
  templates:
    - name: main
      steps:
      - - name: namespace-setup
          templateRef: 
            name: "namespace-template"
            template: "main"
          arguments:
            parameters:
            - name: name
              value: "{{ printf "{{item.name}}" }}"
            - name: annotations
              value: "{{ printf "{{item.annotations}}" }}"
            - name: labels
              value: "{{ printf "{{item.labels}}" }}"
          withParam: "{{ printf "{{workflow.parameters.namespaces}}" }}"
      - - name: deploy-argocd-chart
          templateRef: 
            name: helm-template
            template: main
          arguments:
            parameters:
              - name: releaseName
                value: "{{ printf "{{item.releaseName}}" }}"
              - name: chart
                value: "{{ printf "{{item.chartName }}" }}"
              - name: namespace
                value: "{{ printf "{{item.namespace}}" }}"
              - name: version
                value: "{{ printf "{{item.chartVersion}}" }}"
              - name: url
                value: "{{ printf "{{item.chartsUrl}}" }}"
              - name: configMapName
                value: "{{ printf "{{item.configMapName}}" }}"
          withParam: "{{ printf "{{workflow.parameters.helm}}" }}"
      - - name: deploy-argocd-app
          templateRef: 
            name: argocd-app-template
            template: main
          arguments:
            parameters:
              - name: argoProject
                value: "default"
              - name: argoNamespace
                value: "argo-cd"
              - name: argoLabels
                value: |
                  {}
              - name: targetCluster
                value: "https://kubernetes.default.svc"
              - name: targetNamespace
                value: "{{ printf "{{item.namespace}}" }}"
              - name: helmReleaseName
                value: "{{ printf "{{item.releaseName}}" }}"
              - name: helmChartName
                value: "{{ printf "{{item.chartName }}" }}"
              - name: helmTargetRevision
                value: "{{ printf "{{item.chartVersion}}" }}"
              - name: helmRepoUrl
                value: "{{ printf "{{item.chartsUrl}}" }}"
                {{- $fileName := printf "files/%s.yaml" .Values.workflow.helm.configMapName }}
              - name: helmValues
                value: |
                  {{- .Files.Get $fileName | fromYaml | toJson | nindent 18 }}
          withParam: "{{ printf "{{workflow.parameters.helm}}" }}"
