---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: namespace-template
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "150"
    #"helm.sh/hook-delete-policy": before-hook-creation
spec:
  entrypoint: main
  securityContext:
    runAsNonRoot: true
    runAsUser: 10010

############# Workflow Definition #################
  templates:
  - name: main
    inputs:
      parameters:
      - name: name
      - name: labels
      - name: annotations
    resource:
      action: apply
      manifest: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{inputs.parameters.name}}
          labels:
            {{inputs.parameters.labels}}
          annotations:
            {{inputs.parameters.annotations}}
