# Default values for argoworkflows.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# See https://github.com/argoproj/argo-helm/blob/master/charts/argo-workflows/values.yaml
argoworkflows:
  enabled: true
  nameOverride: "argoworkflows"
  singleNamespace: false
  controller:
    containerRuntimeExecutor: pns
  artifactRepository:
    archiveLogs: true
    s3:
      accessKeySecret:
        key: accesskey
        name: argo-artifacts
      secretKeySecret:
        key: secretkey
        name: argo-artifacts
      bucket: argo-artifacts
      endpoint: argo-artifacts:9000
      insecure: true
  server:
    extraArgs: [ "--auth-mode=server" ]
    ingress:
      enabled: true
      annotations: {}
      #  [ ingress.kubernetes.io/protocol: http ]
      hosts:
        [ "argoworkflow.public.k8s.local" ]
  # workflow:
  #   serviceAccount:
  #     annotations:
  #       eks.amazonaws.com/role-arn: "arn:aws:iam::054273887971:role/baas-argo-workflow-service-account"

minio:
  enabled: true
  fullnameOverride: argo-artifacts
  buckets:
    - name: argo-artifacts
      purge: true
      policy: none
  ingress:
    enabled: true
    # ingressClassName: ""
    labels: {}
    annotations: {}
    #  ingress.kubernetes.io/protocol: http 
    path: /
