# Default values for k8s-bootstrap-wrapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set 
  name: ""




workflow:
  helm:
    chartName: "argo-cd"
    releaseName: son-of-workflow
    chartVersion: "~3.26.1"
    namespace: "argo-cd"
    chartsUrl: https://argoproj.github.io/argo-helm
    configMapName: argocd-chart-values
  namespaces:
  - name: test
    labels:
      iam: working
      soami: "yes"
    annotations:
      my: annotation
  - name: test2
    labels:
      istio-injection: enabled
    annotations:
      my: annotation
  - name: test3
    labels:
      istio-injection: enabled
    annotations: {}
  - name: test4
    labels:
      istio-injection: enabled
    annotations:
      name: "random"
  - name: test5
    labels:
      istio-injection: enabled
    annotations:
      name: "random"

global:
  serviceAccount:
    name: cluster-boot-strapper